info.rkt
main.rkt
main.scrbl

This PR adds support for `lgamma` and `tgamma`.
It wasn't easy! The implementation is based around `convex` and `convex-find-min`, which implement interval versions of convex functions. Basically, `convex-find-min` takes in a convex bigfloat function and two endpoints, and finds the local minimum between those two endpoints using a variant of binary search. That local minimum can then be fed into `convex`.
To use this to implement the Gamma functions, note that `lgamma` is convex on all intervals between two adjacent non-positive integers, and for the positive reals. So the interval version basically splits the input into those intervals. An additional mathematical fact, that the local minima decrease as z -> -inf, is necessary for ranges that cover multiple intervals.
The implementation …

Add interval versions of `lgamma` and `tgamma`

---

main.rkt
test.rkt

This PR modifies the unit test sampler to sometimes sample the singleton intervals containing 0, 1, or -1. This uncovers a host of issues, which this PR then fixes.

Sampling constants reveals bugs in Rival

---

main.rkt

Changed implementation to save execution time. Definition of flags `a` and `b` is done using less operations

Updated ival-sin implementation for saving execution time

---

main.rkt

This PR basically changes `classify-ival` to use sign bits instead of comparisons, which is much faster for the common case of comparing to 0.

Faster multiplication

---

main.rkt

The issue is that clamping called `bfmax2` and `bfmin2` without indicating the rounding direction, thereby accidentally rounding, possibly in the wrong direction, in case of mixed precision.

Make clamping faster and more correct

---

main.rkt
test.rkt

This PR fixes a load of soundness bugs that affected various function when run in mixed-precision mode (that is, when output and input precisions didn't match). It also adds new tests, and then fixes a bunch of bugs that those tests found.

Fix mixed-precision bugs

---

main.rkt

Previously, we didn't have any dynamic parameter to determine how close an input can be to `pi`/`pi/2` when tuning range reduction in trigonometric functions. On this branch, this dynamic parameter is precision of the input, which can make the precision prediction closer to the expected one.

Formula change for input reduction in trig functions

---

main.rkt

This pull request fixes the bug that is associated with exponent calculation for constant `bf` values. Range reduction used to be evaluated with `*rival-precision*` bits of precision because exponent calculations for some constants were not wrong. These constants are:  `-inf.bf +inf.bf +nan.bf -min.bf -max.bf +min.bf +max.bf` - range reduction is redundant, the interval is `'too-wide`

Trig exponent calculation fix

---

main.rkt

The same fix as #21, but unfortunately I fixed exponent calculation for only a single conditional branch of the body, when the fix actually has to be at the top of the body. Now fixed, bug removed

Range reduction fix2

---

main.rkt

The core logic is this:
- Values with exponent < 0 are < 1 and therefore are `near-0`
- Values with ulp > 0 have minimum difference of > 1 and therefore are too wide
- Otherwise, range-reduce
This isn't maximally precise, but points right on the boundary should be rare anyway.

A much simpler and much faster `classify-ival-periodic`

---

main.rkt
test.rkt

This branch introduces two new function called `ival-exact-fabs` and `ival-exact-neg`. These functions work the same as their "inexact" copies - the main difference is - the result of the new functions is evaluated under the precision of input.
Some functions require `exact` versions for correctness, they are: `ival-fmod`, `ival-remainder` and etc.

Exact ival-fabs ival-neg

---

main.rkt

This is safe because MPFR uses a normalized representation, so the smallest representable value is the same at all precisions (not the case for the largest representable value).

Fix the high endpoint from an underflowing `exp`

---

ops.rkt

This PR combines two core optimizations:
- Use `mpfr-sign` (a struct accessor) instead of `bf-signbit` (a confusing wrapper around it)
- Specialize `classify-ival` for the use case in `pow` where we need to classify positive intervals for bigger/smaller than 1
- Specialize `classify-ival-strict` for the only use case of classifying around 0

Speed up `classify-ival`

---

time.rkt

This PR adds a "total" row at the foot of the table, so we can see the contribution to the total from unsamplable, valid, and invalid points. There's also an `--id` flag that lets you rerun a single benchmark on the command line, for performance work.

Various improvements to the nightlies

---

eval/compile.rkt
ops.rkt
time.rkt

This PR puts `(pow x 2)` and `(fma x y z)` into the compiler, removing a conditional from inside `pow`. It also make a variety of tiny changes to conditionals to use the sign bit. Finally, it removes the call to `exp` from inside `ival-pow-pos` by refactoring `overflows-loose-at` in order to make it callable directly.

Minor speedups

---

eval/adjust.rkt
eval/compile.rkt
eval/machine.rkt
eval/main.rkt
eval/run.rkt

This PR speeds up Rival evaluation with two tweaks:
- Use an flvector for timing information, which should avoid some boxing
- Convert to float once and store slack information for later instead of recomputing it

Faster Rival evaluation

---

ops/core.rkt

This bug must have been here since, what, 2020?

Fix the endpoints of division when you do `x / [!0, y]`

---

eval/compile.rkt

This PR fixes https://github.com/herbie-fp/herbie/issues/842 by making the compiler a bit smarter about `pow`.

Fix handling of fractional `pow`

---

eval/repl.rkt

This PR adds a command, `(explain f args ...)`, to the Rival repo. This generates an ASCII table showing the precision and time for executing each command at each iteration:
```
> (define (cos2 x e) (- (cos x) (cos (+ x e))))
> (explain cos2 1e300 1e-300)
Executed 4 instructions for 2 iterations:
cos           78  349.85     592  205.08    1695  191.16
add           83   23.93    2107   10.99    2698   10.99
cos           78   10.99     593  188.96    1695  283.94
sub           73   19.04      73   10.99      73   10.99
adjust                             50.05           22.95
Total: 1.922ms
> exit
```
Honestly, some of the numbers are kind-of hard to believe (why does `add` get faster at higher precision? Same for `cos`) but that can presumably be fixed later, as can some more labels for …

Add "explain" mode to Rival repl

---

eval/repl.rkt
eval/run.rkt

This PR makes the `explain` output a little nicer. First, there's a table with totals:
```
> (define (cos2 x e) (- (cos x) (cos (+ x e))))
> (explain cos2 1e300 1e-300)
Executed 4 instructions for 3 iterations:
Oper.  Bits  Time  Bits  Time  Bits  Time
------------------------------------------
adjust                    22.9        21.0
cos    78  75.9   592  98.9  1695 173.1
add    83  11.0  2107  10.0  2698  11.0
cos    78   8.1   593  99.1  1695 176.0
sub    73  10.0    73  10.0    73  11.0
------------------------------------------
Total       105.0       241.0       392.1
Total: 0.857ms
```
Plus, I now apply once before profiling; this avoids cache issues and produces much nicer numbers, more representative of running several points through.

Make the explain output nicer

---

eval/main.rkt

Early exit wasn't working before

Skip running an iter if adjusting made us go over

---

ops/all.rkt
ops/core.rkt
ops/gamma.rkt

This PR fixes #64, which turns out to be an issue with the handling of negative infinite endpoints in `lgamma`.

Fix `lgamma` for [-inf, +x]

---

eval/run.rkt

Sometimes, a point was sampled as valid even though it was invalid:
```
> (eval (sqrt (- (exp -1e100))))
0.0
```
This is because `sqrt` was returning the interval `[0, 0]` with the `err?` flag set, and then this was being taken as a point interval. This PR fixes it.

Fix some invalid points sampled as valid

---

eval/adjust.rkt

I believe that this bug was introduced with safe-sampling-feature by itself.
The problem is: we increase everything with slack hoping that the new results will be better,
However the machine skips all the evaluation because `vrepeats` vector was pitched previously with `#t` for all the instructions

Safe sampling feature fix

---

eval/main.rkt

This branch adds a one additional iteration when a maximum was reached instead of exiting immediately. 
This is an addition to #67 which fixes early stopping in general.

Loose early stopping

---

eval/compile.rkt
eval/machine.rkt
eval/run.rkt
repl.rkt
scribblings/eval.scrbl
utils.rkt

This PR makes each discretization list a target precision instead of always defaulting to 73. Among other things, this makes `(set precision ...)` work in the REPL (#70). Previously, if you set a precision higher than 73, we'd never tune the precision high enough to converge.

Target precisions in discretizations

---

eval/adjust.rkt
mpfr.rkt

It looks like the special constants for the `mpfr-exp` of 0 and infinity are platform-specific somehow. Maybe it's 32-bit vs 64-bit? Or Windows ABI something something? Anyway, better not to mess with it.

Fix Rival on Windows by using `bfinfinite?` and `bfzero?`

---

eval/compile.rkt
mpfr.rkt
ops/all.rkt
ops/trig.rkt

This PR adds the `cosu`, `tanu`, and `sinu` functions to Rival. It also treats them as shorthands for `(cos (* (/ x n) (PI)))` and similar. I didn't add every possible shorthand—there would be too many—but we can add them if necessary. The code for each function isn't that bad (though more compression is always nice).

Add support for `cosu` and friends

---

.github/workflows/tests.yml
Makefile
README.md
eval/adjust.rkt
eval/compile.rkt
eval/machine.rkt
eval/main.rkt
eval/run.rkt
info.rkt
infra/format-mathematica.rkt
infra/generate-points.rkt
infra/interval-evaluate.rkt
infra/report.rkt
infra/run-mathematica.rkt
infra/run-mpfi.rkt
main.rkt
mpfr.rkt
ops/all.rkt
ops/core.rkt
ops/fmod.rkt
ops/gamma.rkt
ops/pow.rkt
ops/trig.rkt
profile.rkt
repl.rkt
test.rkt
time.rkt
utils.rkt

This PR doesn't actually reformat anything yet (probably want everything merged and the repo quiet before we do that) but it adds a CI step that fails if `raco fmt` doesn't like your formatting. Which will allow us to enforce the formatting.

Switch to `raco fmt` for formatting

---

eval/adjust.rkt

This branch introduces a fix correlated to the `useful` optimization.
Currently, benchmark 380 doesn't work properly on main due to a bug. 
The bug is fixed and likely to be inside `precision-tuning` function. However, an addition exploration is needed.
Maybe right now, the `useful` optimization is slightly greedy and can be optimized further.

Useful fix

---

Makefile
eval/adjust.rkt

This PR fixes the `minlog` function so that `minlog([0, 0])` doesn't accidentally assign an enormous precision for no reason.

Don't freak out when the difference between two values is exactly 0

---

eval/compile.rkt
ops/core.rkt

Despite that #85 was not merged, it revealed a room for improvement that may save runtime.
This PR adds two optimizations to the `rival-compile` functionality that will allow us to overflow less.

Few optimizations to prevent overflows at some particular benchmarks

---

repl.rkt

This PR introduces a little typecheck for Rival's repl.
The bug was discovered by @bksaiki when trying a simple example in Rival's repl:
```
> (define (f) (> (+ (/ 2 5) (/ 1 5)) (/ 3 5)))
> (eval f)
mpfr->C: argument is not non-null `mpfr' pointer
argument: #f
context...:
/opt/racket/8.14/share/pkgs/math-lib/math/private/bigfloat/mpfr.rkt:900:0: bigfloat->ordinal
/opt/racket/8.14/share/pkgs/math-lib/math/private/bigfloat/mpfr.rkt:925:0: bigfloats-between
/opt/racket/8.14/share/pkgs/typed-racket-lib/typed-racket/utils/simple-result-arrow.rkt:39:12
/home/bsaiki/.local/share/racket/8.14/pkgs/rival/utils.rkt:17:18
/home/bsaiki/.local/share/racket/8.14/pkgs/rival/eval/run.rkt:68:0: rival-machine-return
/home/bsaiki/.local/share/racket/8.14/pkgs/rival/eval/main.rkt:65:0: rival-apply …
```

Adding boolean discretization for repl

---

.github/workflows/distribute.yml
.gitignore
Makefile

This pull request updates a set of rules of `Makefile` by adding a `distribution` rule which compiles an executable for Rival's REPL (read–evaluate–print loop).

Distribution for Rival's REPL

---

eval/adjust.rkt
eval/machine.rkt
eval/main.rkt
eval/tests.rkt
main.rkt

This PR continues #87 story.
I didn't realize at that time, but `rival-analyze` also can use hints to reduce computational path.
It can be used in Herbie at analyze stage when we split hyperrects.
The thing is that a hint from hyperrect `[a, b]` can be used at `[a, a+b/2]` and `[a+b/2, b]` hyperrects when applying `rival-analyze`.
At the current time we are just dropping this hint, but it can be reused further and some time can be saved.

Analyze hint usage

---

eval/adjust.rkt
eval/main.rkt

This PR fixes an issue that has been observed with `make-hint` function.
It has been observed that `make-hint` was not deterministic and could produce different results for the same hyperrects with and without a _hint_.
An issue have been found.
In the current implementation, a _hint_ for instruction `(list ival-fmax arg1 arg2)` was calculated as:
take `arg1` register and `arg2` register, compare them and then decide which path to choose.
But there is an issue with that:
Imagine that we are using a _hint_ that have marked `fmax` as `1` - which means "execute only `arg1`".
Therefore, `arg2` just was not executed at all, `arg2` register stores some nonsense from previous runs.
When making new _hint_, we still access this memory and compare nonsense with valid interval.
Thus, the results of …

New hint propogation using old hint as a guide

---

eval/compile.rkt

An interesting bug was discovered by @bksaiki!
```
$ racket -l rival
> (define (f x) x)
in-vector: contract violation
expected: exact-nonnegative-integer?
given: -1
context...:
/opt/racket/8.14/collects/racket/private/for.rkt:973:2: check-ranges
/opt/racket/8.14/collects/racket/private/for.rkt:1002:2: normalise-inputs
/home/bsaiki/research/herbie-fp/rival/eval/compile.rkt:308:0: setup-vstart-precs
/home/bsaiki/research/herbie-fp/rival/eval/compile.rkt:267:0: rival-compile
/home/bsaiki/research/herbie-fp/rival/repl.rkt:107:0: repl-save-machine!
/home/bsaiki/research/herbie-fp/rival/repl.rkt:247:2
body of (submod "/home/bsaiki/research/herbie-fp/rival/main.rkt" main
```
For some reasons, Rival didn't want to compile a simple expression.
The bug was found, the reason behind is that …

Fix of function that assigns `base-tuning` precisions

---

.gitignore
eval/main.rkt
eval/run.rkt
infra/histograms.py
infra/repeats_plot.py
infra/run-baseline.rkt
main.rkt
time.rkt

This PR adds the following features to "Baseline":
1) Hint support, this is done in order to compare Rival and Baseline performances on Herbie's main. Currently main _supports_ hints, therefore, for a fair comparison it is necessary.
2) Including *useful?* feature to Baseline. The feature allows to skip reevaluating fixed intervals. The feature is originally from Rival's backward pass, however, it has less something to do with the tuning algorithm and probably can be added to Baseline as well in order to compare two tuning algorithms fairly.
3) Since adding *useful?* feature to Baseline, it means that Baseline also has some `adjust` time now, therefore, **histogram** plots were updated so that Baseline would also have a tuning column + **repeat** plot got updated since Baseline now also …

Baseline updates

---

eval/compile.rkt

That's slightly crazy to think, but an optimization as `(pow (E) x)` -> `(exp x)` can be very critical in performance.
This issue was discovered in Herbie, here are two screenshots of with and without the rewrite.
And all this is for just a simple benchmark `Logarithmic Transform`:
```
(FPCore (c x y)
:precision binary64
(* c (log (+ 1.0 (* (- (pow E x) 1.0) y)))))
```

Parsing optimization of `pow E x` to `exp x`

---

ops/fmod.rkt

This PR fixes #96; basically, we weren't setting rounding direction for some "exact" operations, which aren't exact with mixed precision. I have now tried 100k tests for `bfremainder` with no failures.

Fix a subtle bug in `bfremainder` mixed-precision

---

README.md
eval/adjust.rkt
eval/compile.rkt
eval/tricks.rkt
infra/run-baseline.rkt
mpfr.rkt
ops/all.rkt
ops/arith.rkt
ops/core.rkt

This PR adds the `ival-add!`, `ival-sub!`, `ival-mult!`, and `ival-div!` operators, which are in three-argument form. These have a kind-of weird API: they still _return_ the output interval, but they are allowed to use their first argument as pre-allocated space when doing so. In any case, the point of this all is that we can avoid allocating in the hot loop, which should make not only later but also first iterations faster.
The arithmetic operators are by far the majority of the run time, so handling just these four is sensible. In fact, multiplication is 30% of run time on its own. (Note that multiplication has a case where it constructs two different intervals and unions them; this still requires some allocation.)
A big current flaw with this PR is that the pre-allocated values are …

Add imperative interval operators that allocate less

---

eval/adjust.rkt
eval/compile.rkt
eval/machine.rkt
eval/run.rkt
eval/tricks.rkt
infra/repeats_plot.py
infra/run-baseline.rkt

This PR resolves a confusion of using `hint` mechanism for _constant_ subexpressions evaluation skips.
Particularly speaking, it was decided that _constant skips_ have more to do with `repeats` rather then `hint`.
This PR implements it by changing `rival-machine` structure by a little:
We need new features of the `machine`, such as: `initial-repeats` vector which would point which instructions should be skipped at the initial iteration; additionally, we need a vector that would store the maximum precisions constant operations got evaluated under - this info will go into `backward-pass`
Additionally, this PR gets rid of `vuseful` vector which used to be created at each tuning  pass. 
Turned out, that the _useful_ logic can be associated with `vrepeats` vector - which is already allocated

Cleanup of "constant skips"

---

ops/pow.rkt
test.rkt

This PR fixes #105 and fixes #106; basically, there was an off by one because `mpfr-exp` is offset by 1 from the actual exponent.

Fix near-underflows in `ival-pow`

---

eval/tests.rkt
ops/core.rkt

Basically, the `fmod` code sometimes involves calling `fabs` and it also sometimes depends on the precision of its arguments for intermediate computations. But it turns out that `fabs` sometimes returns 0 (for intervals that cross 0) and this 0 is the wrong precision (too high), which breaks refinement. The solution is to make a `0` of the correct precision.

Fix pretty subtle "bug" #110 in `fmod`

---

eval/adjust.rkt
eval/compile.rkt
eval/machine.rkt
eval/tricks.rkt

This PR introduces changes to Rival's exponent tricks.
Particularly speaking, tuning formulas for `tanu`, `cosu` and `sinu` have been added.
It is quite interesting that we never ran into this before. One of the reasons why is that Linux uses an older version of MPFR - and we mostly use Linux.
The bug was discovered by @JonasRegehr when using Rival on MacOS.
The new exponent tricks are pretty straight forward, but the fact that the angle for `tanu`, etc. is not stored as an `ival` makes the code slightly tricky, as this angle needs to be stored somewhere since it participates in precision tuning.
I store this angle constant into a new `rival-machine` field called `constant-lookup` - this is a vector to where we can add constants like this now on that do not participate in evaluation, but …

Adding tuning formulas for `tanu`, `cosu` and `sinu`, fix #112

---

ops/fmod.rkt
scribblings/core.scrbl
test.rkt

Refinement is the property that, if `A ⊆ B`, then `f(A) ⊆ f(B)`. I thought all of our functions guaranteed this, but actually `ival-fmod` and `ival-remainder` don't; that's at the core of #111. This PR fixes #111 by explicitly turning off tests for refinement for these two functions.
Ideally we'd document our guarantees and implementation quality for each operator.

Document that `ival-fmod` and `ival-remainder` fail refinement

---

eval/compile.rkt
eval/machine.rkt
eval/main.rkt
infra/run-baseline.rkt
mpfr.rkt
ops/arith.rkt
ops/core.rkt
time.rkt

This PR unifies mutable and immutable bigfloats, as in, they are allocated in the same way. Basically, `new-mpfr` allocates a standard "immutable" bigfloat of `*rival-max-precision*` bits. Then, instead of using `mpfr-set-prec!` you use `set-mpfr-prec!` to directly modify the precision field of the `mpfr_t`; since we "promise" that we only set this to precisions below the max precision this is safe.
I'd like to be more rigorous about using the saved machine precision vs `*rival-machine-precision*` and maybe have some more tests but seems OK as a start.

Unify the allocation strategy for mutable and immutable bigfloats
